# simplified version of the upstream travis configuration.
# automated acceptance test is run[in linux box] for raft, istanbul and clique consensus in parallel as part of every build
# unit test is run in linux and macOS boxes as part of every build

language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false

env:
  global:
  - TESSERA_JAR="$HOME/tessera.jar"

addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:ethereum/ethereum
    - sourceline: ppa:openjdk-r/ppa
    packages:
    - openjdk-8-jdk
    - dpkg # fixes issue with dpkg-deb error due to travis image
    - openssh-client
    - dnsutils
    - maven
    - solc
    - jq
    - curl

before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then git clone https://github.com/amalrajmani/quorum-acceptance-tests.git $TRAVIS_HOME/quorum-acceptance-tests; fi;
- if [ $TRAVIS_OS_NAME = linux ]; then sudo chmod 755 $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh; fi;
- if [ $TRAVIS_OS_NAME = linux ]; then sudo chmod 755 $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh; fi;

matrix:
  include:
  - name: linux-raft
    os: linux
    dist: trusty
    sudo: true
    go: 1.10.x

    cache:
    directories:
    - $HOME/.m2

    env:
    - TF_VAR_consensus_mechanism=raft

    install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh

    script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh


  - name: linux-istanbul
    os: linux
    dist: trusty
    sudo: true
    go: 1.10.x

    directories:
    - $HOME/.m2

    env:
    - TF_VAR_consensus_mechanism=istanbul

    install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh

    script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh

  - name: linux-clique
    os: linux
    dist: trusty
    sudo: true
    go: 1.10.x

    directories:
    - $HOME/.m2

    env:
    - TF_VAR_consensus_mechanism=clique

    install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh

    script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh

  - os: linux
    dist: trusty
    sudo: required
    go: 1.10.x
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - go run build/ci.go test -coverage $TEST_PACKAGES


  - os: osx
    osx_image: xcode9.2 # so we don't have to deal with Kernel Extension Consent UI which is never possible in CI
    go: 1.10.x
    sudo: required
    script:
    - brew update
    - brew install caskroom/cask/brew-cask
    - brew cask install osxfuse
    - go run build/ci.go install
    - go run build/ci.go test -coverage $TEST_PACKAGES

